<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ishan-Macs-MacBook-Pro.local" name="com.framework.TestCases.Scenario3_VerifyFilters" tests="1" failures="1" timestamp="18 Feb 2018 08:51:40 GMT" time="19.753" errors="0">
  <testcase name="Scenario3" time="19.753" classname="com.framework.TestCases.Scenario3_VerifyFilters">
    <failure type="java.lang.AssertionError" message="Test Scenario failed at Step --&gt;&#039; User verifies all the Poducts for keyword &#039;bikerJack&#039;  &#039;. Error is: java.lang.Exception: Following Products are present on the page without keyword &#039;bikerJack&#039; : [ARMA Isabella leren jack met doorgestikte details en inzet van jersey, ARMA Lamb Caprito Tarina jas van lamsleer met kabelgebreide kraag]">
      <![CDATA[java.lang.AssertionError: Test Scenario failed at Step -->' User verifies all the Poducts for keyword 'bikerJack'  '. Error is: java.lang.Exception: Following Products are present on the page without keyword 'bikerJack' : [ARMA Isabella leren jack met doorgestikte details en inzet van jersey, ARMA Lamb Caprito Tarina jas van lamsleer met kabelgebreide kraag]
	at org.testng.Assert.fail(Assert.java:94)
	at com.framework.TestCases.Scenario3_VerifyFilters.Scenario3(Scenario3_VerifyFilters.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- Scenario3 -->
</testsuite> <!-- com.framework.TestCases.Scenario3_VerifyFilters -->
